### PR TITLE
Day1 branch

### PR DESCRIPTION
**Pull request by Charzy-1**
Files created are:
index.html file that bears a heading "Hello Chill Academy"
.css file that was used in styling the heading
.ignore file that i used to hide some irrelevant files like my .md text and node modules

### CODE REVIEW

**Review by basitali111 — CHANGES_REQUESTED** [review]
# Required Changes ♻️

Hi @Charzy-1 ,

Code review blocked: Linters not used.
They catch bugs, enforce style, and improve quality.
Fix linter warnings, then resubmit for full review.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff
# Highlights
✔️ Professional Readme
✔️ Correct Gitflow
## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Charzy-1** [comment]
Hello @basitali111 
I have added the necessary corrections made. Please feel free to look at it.

kind regards

**Review by Pamphilemkp — APPROVED** [review]
Hi @Charzy-1 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights
- No linter errors ✅  
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Kindly make use of the provided README.md template provided in your dashboard otherwise the next project will be marked as invalid

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @pamphilemkp

------
_As described in the Code reviews limits policy  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion by contacting us.

**Comment by Charzy-1** [comment]
Hi. please check the request again and see if there are things
still missing.

Thanks

**Comment by Charzy-1** [comment]
Thanks for your assistance.

**Pull request merged**
